export const COMPANY_INFO = {
  name: "SREE MANIKANTA CABLES AND CONDUCTORS",
  tagline: "Manufacturing of Wires, Cables and Conductors",
  address: "Survey No. 317 & 318, Dommara Pochampally Village, Quthbullapur Mandal, Medchal Malkajgiri District, Hyderabad – 500043, Telangana, India.",
  phone: "+91 9121224544 / +91 9121224545",
  email: "sreemanikantacables@gmail.com",
  website: "www.sreemanikantacables.com / www.sreemanikantacables.in",
  established: 2010,
  employees: 150,
  certifications: ["ISO 9001:2015", "ISO 14001:2015", "ISO 45001:2018", "ISI Marked", "CPRI Approved", "BIS Certified"],
} as const;

export const NAVIGATION_ITEMS = [
  { label: "Home", href: "/" },
  { label: "About Us", href: "/about" },
  {
    label: "Products",
    href: "/products",
    children: [
      { label: "Industrial Cables", href: "/products/industrial-cables" },
      { label: "Control Cables", href: "/products/control-cables" },
      { label: "LT Power Cables", href: "/products/lt-power-cables" },
      { label: "Instrumentation Cables", href: "/products/instrumentation-cables" },
      { label: "Flexible Cables", href: "/products/flexible-cables" },
      { label: "House Wires", href: "/products/house-wires" },
      { label: "Solar Cables", href: "/products/solar-cables" },
      { label: "Special Purpose Cables", href: "/products/special-purpose-cables" },
    ],
  },
  { label: "Manufacturing", href: "/manufacturing" },
  { label: "Quality", href: "/quality" },
  { label: "Digital Presence", href: "/digital" },
  { label: "Contact", href: "/contact" },
] as const;

export const PRODUCT_CATEGORIES = [
  {
    id: "industrial-cables",
    name: "Industrial Cables",
    slug: "industrial-cables",
    description: "High-performance industrial cables designed for demanding applications in manufacturing, automation, and heavy machinery.",
    icon: "factory",
    image: "/images/products/industrial-cables.jpg",
  },
  {
    id: "control-cables",
    name: "Control Cables",
    slug: "control-cables",
    description: "Precision control cables for signal transmission in industrial automation, robotics, and process control systems.",
    icon: "cpu",
    image: "/images/products/control-cables.jpg",
  },
  {
    id: "lt-power-cables",
    name: "LT Power Cables",
    slug: "lt-power-cables",
    description: "Low tension power cables for efficient power distribution in commercial, industrial, and residential applications.",
    icon: "zap",
    image: "/images/products/lt-power-cables.jpg",
  },
  {
    id: "instrumentation-cables",
    name: "Instrumentation Cables",
    slug: "instrumentation-cables",
    description: "Specialized instrumentation cables for accurate signal transmission in process instrumentation and control systems.",
    icon: "gauge",
    image: "/images/products/instrumentation-cables.jpg",
  },
  {
    id: "flexible-cables",
    name: "Flexible Cables",
    slug: "flexible-cables",
    description: "Highly flexible cables for dynamic applications, robotics, cable chains, and moving equipment.",
    icon: "rotate-ccw",
    image: "/images/products/flexible-cables.jpg",
  },
  {
    id: "house-wires",
    name: "House Wires",
    slug: "house-wires",
    description: "Premium house wiring cables for safe and reliable electrical installations in residential and commercial buildings.",
    icon: "home",
    image: "/images/products/house-wires.jpg",
  },
  {
    id: "solar-cables",
    name: "Solar Cables",
    slug: "solar-cables",
    description: "UV-resistant solar cables designed for photovoltaic systems and renewable energy installations.",
    icon: "sun",
    image: "/images/products/solar-cables.jpg",
  },
  {
    id: "special-purpose-cables",
    name: "Special Purpose Cables",
    slug: "special-purpose-cables",
    description: "Custom-engineered cables for specialized applications including marine, defense, and hazardous environments.",
    icon: "settings",
    image: "/images/products/special-purpose-cables.jpg",
  },
] as const;

export const MANUFACTURING_STAGES = [
  {
    id: "raw-material",
    title: "Raw Material Procurement",
    stage: "Raw Material",
    description: "We source premium-grade copper, aluminum, and insulation materials from certified suppliers with full traceability.",
    icon: "package",
    image: "/images/manufacturing/raw-material.jpg",
    features: [
      "99.99% Pure Copper Cathodes",
      "High-Grade Aluminum Rods",
      "PVC/XLPE/HRPVC Compounds",
      "Certified Supplier Network",
    ],
    equipment: ["Spectrometer", "Tensile Tester", "Chemical Analyzer"],
    qualityChecks: [
      "Material Composition Analysis",
      "Conductivity Testing",
      "Dimensional Verification",
      "Visual Inspection",
    ],
  },
  {
    id: "wire-drawing",
    title: "Wire Drawing & Stranding",
    stage: "Manufacturing",
    description: "Precision wire drawing and stranding using state-of-the-art machines to achieve optimal conductivity and flexibility.",
    icon: "git-branch",
    image: "/images/manufacturing/wire-drawing.jpg",
    features: [
      "Multi-Wire Drawing Machines",
      "Planetary Stranding",
      "Bunch Stranding",
      "Compact & Compressed Stranding",
    ],
    equipment: [
      "Single Block Drawing Machines",
      "Multi-Wire Drawing Lines",
      "Planetary Stranding Machines",
      "Bunching Machines",
    ],
    qualityChecks: [
      "Diameter Measurement",
      "Surface Quality Check",
      "Lay Length Verification",
      "Mechanical Properties",
    ],
  },
  {
    id: "insulation",
    title: "Insulation & Sheathing",
    stage: "Manufacturing",
    description: "Advanced extrusion lines for uniform insulation and sheathing with superior electrical and mechanical properties.",
    icon: "shield",
    image: "/images/manufacturing/insulation.jpg",
    features: [
      "PVC Insulation (Type A, B, C)",
      "XLPE Insulation",
      "HRPVC / HFFR Sheathing",
      "Multi-Layer Extrusion",
    ],
    equipment: [
      "High-Speed Extrusion Lines",
      "Triple Layer Extrusion",
      "Cross-Head Dies",
      "Online Diameter Gauges",
    ],
    qualityChecks: [
      "Thickness Measurement",
      "Eccentricity Check",
      "Spark Testing",
      "Hot Set Test (XLPE)",
    ],
  },
  {
    id: "armouring",
    title: "Armouring & Screening",
    stage: "Manufacturing",
    description: "Robust armouring and screening for mechanical protection and electromagnetic compatibility.",
    icon: "lock",
    image: "/images/manufacturing/armouring.jpg",
    features: [
      "Galvanized Steel Wire Armour",
      "Aluminum Wire Armour",
      "Steel Tape Armour",
      "Copper Wire Braid Screening",
    ],
    equipment: [
      "Armouring Machines",
      "Braiding Machines",
      "Taping Machines",
      "Serving Machines",
    ],
    qualityChecks: [
      "Armour Coverage %",
      "Braid Coverage %",
      "Adhesion Test",
      "Dimensional Check",
    ],
  },
  {
    id: "testing",
    title: "Quality Testing",
    stage: "Quality Testing",
    description: "Comprehensive testing at every stage ensuring compliance with national and international standards.",
    icon: "check-circle",
    image: "/images/manufacturing/testing.jpg",
    features: [
      "Routine Tests (100%)",
      "Type Tests (Per Standard)",
      "Acceptance Tests",
      "Special Tests on Request",
    ],
    equipment: [
      "High Voltage Test Sets",
      "Impulse Generators",
      "Partial Discharge Detectors",
      "Ageing Ovens",
    ],
    qualityChecks: [
      "Conductor Resistance",
      "Insulation Resistance",
      "High Voltage Test",
      "Flame Retardant Test",
    ],
  },
  {
    id: "packaging",
    title: "Packaging & Delivery",
    stage: "Packaging & Delivery",
    description: "Professional packaging solutions ensuring safe transit and easy handling at customer sites.",
    icon: "truck",
    image: "/images/manufacturing/packaging.jpg",
    features: [
      "Wooden Drums (ISI Marked)",
      "Steel Drums",
      "Coils with Shrink Wrap",
      "Custom Length Cutting",
    ],
    equipment: [
      "Automatic Drum Winding",
      "Length Measuring Devices",
      "Printing & Marking Machines",
      "Forklift & Crane Facility",
    ],
    qualityChecks: [
      "Drum Dimension Check",
      "Length Verification",
      "Marking Legibility",
      "Sealing Integrity",
    ],
  },
] as const;

export const QUALITY_CERTIFICATIONS = [
  {
    id: "iso9001",
    name: "ISO 9001:2015",
    issuer: "TUV Rheinland",
    year: 2024,
    validity: "2024-2027",
    image: "/images/certifications/iso9001.jpg",
    description: "Quality Management System certification covering design, development, manufacturing, and supply of wires and cables.",
  },
  {
    id: "iso14001",
    name: "ISO 14001:2015",
    issuer: "TUV Rheinland",
    year: 2024,
    validity: "2024-2027",
    image: "/images/certifications/iso14001.jpg",
    description: "Environmental Management System certification demonstrating commitment to sustainable manufacturing practices.",
  },
  {
    id: "iso45001",
    name: "ISO 45001:2018",
    issuer: "TUV Rheinland",
    year: 2024,
    validity: "2024-2027",
    image: "/images/certifications/iso45001.jpg",
    description: "Occupational Health & Safety Management System ensuring safe and healthy workplace for all employees.",
  },
  {
    id: "isi",
    name: "ISI Mark (BIS)",
    issuer: "Bureau of Indian Standards",
    year: 2024,
    validity: "2024-2025",
    image: "/images/certifications/isi.jpg",
    description: "BIS certification for various cable types confirming compliance with Indian Standards specifications.",
  },
  {
    id: "cpri",
    name: "CPRI Approved",
    issuer: "Central Power Research Institute",
    year: 2024,
    validity: "2024-2026",
    image: "/images/certifications/cpri.jpg",
    description: "Central Power Research Institute approval for power cables confirming type test compliance.",
  },
  {
    id: "fire",
    name: "Fire Survival Cables",
    issuer: "Loss Prevention Council (LPC)",
    year: 2023,
    validity: "2023-2026",
    image: "/images/certifications/fire.jpg",
    description: "LPCB certification for fire-resistant cables maintaining circuit integrity during fire conditions.",
  },
] as const;

export const QUALITY_TESTS = [
  {
    id: "conductor-resistance",
    name: "Conductor Resistance Test",
    standard: "IS 8130 / IEC 60228",
    description: "Measurement of DC resistance of conductor at 20°C to verify conductivity and cross-sectional area.",
    equipment: "Kelvin Double Bridge / Micro-ohmmeter",
    frequency: "Every Coil (Routine)",
  },
  {
    id: "insulation-resistance",
    name: "Insulation Resistance Test",
    standard: "IS 5831 / IEC 60502",
    description: "Measurement of insulation resistance to verify insulation quality and detect defects.",
    equipment: "Megger / Insulation Tester (5kV)",
    frequency: "Every Coil (Routine)",
  },
  {
    id: "high-voltage",
    name: "High Voltage Test",
    standard: "IS 1554 / IEC 60502",
    description: "Application of AC high voltage to verify insulation integrity and withstand capability.",
    equipment: "HV Test Set (up to 65kV AC)",
    frequency: "Every Coil (Routine)",
  },
  {
    id: "spark-test",
    name: "Spark Test",
    standard: "IS 5831 / IEC 60502",
    description: "Online continuous spark testing during extrusion to detect insulation defects.",
    equipment: "Online Spark Tester (10kV AC)",
    frequency: "Continuous (In-Process)",
  },
  {
    id: "flame-retardant",
    name: "Flame Retardant Test",
    standard: "IEC 60332-1 / IS 10810-53",
    description: "Vertical flame propagation test for single cable to verify flame retardant properties.",
    equipment: "Flame Test Chamber",
    frequency: "Type Test / Sample Basis",
  },
  {
    id: "fire-survival",
    name: "Fire Survival Test (CWZ)",
    standard: "IEC 60331 / BS 6387",
    description: "Circuit integrity test under fire conditions with mechanical shock and water spray.",
    equipment: "Fire Survival Test Chamber",
    frequency: "Type Test",
  },
  {
    id: "ageing",
    name: "Ageing Test",
    standard: "IS 5831 / IEC 60502",
    description: "Accelerated ageing in air oven to verify long-term insulation performance.",
    equipment: "Ageing Oven (100-135°C)",
    frequency: "Type Test",
  },
  {
    id: "partial-discharge",
    name: "Partial Discharge Test",
    standard: "IEC 60885 / IEEE 48",
    description: "Detection of partial discharges in HV cables to ensure insulation quality.",
    equipment: "PD Detection System",
    frequency: "Type Test / Special Test",
  },
] as const;

export const DIGITAL_FEATURES = [
  {
    id: "seo",
    title: "SEO Optimization",
    description: "Comprehensive search engine optimization strategy to improve visibility and attract qualified industrial leads.",
    icon: "search",
    image: "/images/digital/seo.jpg",
    features: [
      "Technical SEO Audit",
      "Keyword Research & Strategy",
      "On-Page Optimization",
      "Schema Markup Implementation",
      "Core Web Vitals Optimization",
      "Local SEO for Manufacturing",
    ],
    benefits: [
      "Higher Search Rankings",
      "Increased Organic Traffic",
      "Qualified Lead Generation",
      "Better ROI on Marketing",
    ],
  },
  {
    id: "performance",
    title: "Website Performance",
    description: "Lightning-fast website with optimized loading speeds, ensuring seamless user experience across all devices.",
    icon: "zap",
    image: "/images/digital/performance.jpg",
    features: [
      "Next.js 14+ App Router",
      "Edge Runtime Deployment",
      "Image Optimization (WebP/AVIF)",
      "Code Splitting & Lazy Loading",
      "CDN Integration",
      "Lighthouse Score 95+",
    ],
    benefits: [
      "Sub-2s Load Times",
      "Improved Conversion Rates",
      "Better Search Rankings",
      "Reduced Bounce Rates",
    ],
  },
  {
    id: "engagement",
    title: "Customer Engagement",
    description: "Interactive features and personalized experiences to engage visitors and convert them into long-term clients.",
    icon: "users",
    image: "/images/digital/engagement.jpg",
    features: [
      "Live Chat Integration",
      "Product Configurator",
      "Interactive Catalogs",
      "Quote Request Forms",
      "WhatsApp Business API",
      "Multi-language Support",
    ],
    benefits: [
      "Higher Engagement Rates",
      "Faster Query Resolution",
      "Personalized Experience",
      "Increased Inquiries",
    ],
  },
  {
    id: "cms",
    title: "Content Management",
    description: "Robust content management system for easy updates of products, certifications, and company information.",
    icon: "file-text",
    image: "/images/digital/cms.jpg",
    features: [
      "Headless CMS Integration",
      "Product Catalog Management",
      "Dynamic Page Builder",
      "Multi-user Workflows",
      "Version Control",
      "Automated Backups",
    ],
    benefits: [
      "Easy Content Updates",
      "Consistent Branding",
      "Faster Time-to-Market",
      "Team Collaboration",
    ],
  },
  {
    id: "analytics",
    title: "Google Analytics & Insights",
    description: "Advanced analytics and tracking to measure performance, understand user behavior, and optimize conversions.",
    icon: "bar-chart",
    image: "/images/digital/analytics.jpg",
    features: [
      "GA4 Implementation",
      "Enhanced E-commerce Tracking",
      "Custom Event Tracking",
      "Conversion Funnel Analysis",
      "Heatmaps & Session Recording",
      "Custom Dashboards",
    ],
    benefits: [
      "Data-Driven Decisions",
      "Audience Intelligence",
      "Conversion Optimization",
      "ROI Measurement",
    ],
  },
  {
    id: "branding",
    title: "Online Branding",
    description: "Strategic digital branding to establish industry authority and build trust with industrial buyers.",
    icon: "globe",
    image: "/images/digital/branding.jpg",
    features: [
      "Corporate Identity Design",
      "Social Media Management",
      "Content Marketing Strategy",
      "Industry Thought Leadership",
      "PR & Media Outreach",
      "Reputation Management",
    ],
    benefits: [
      "Brand Recognition",
      "Industry Authority",
      "Trust Building",
      "Competitive Advantage",
    ],
  },
  {
    id: "growth",
    title: "Business Growth",
    description: "Integrated digital strategies driving measurable business growth through lead generation and client acquisition.",
    icon: "trending-up",
    image: "/images/digital/growth.jpg",
    features: [
      "Lead Generation Campaigns",
      "Account-Based Marketing",
      "Email Marketing Automation",
      "PPC Campaign Management",
      "Conversion Rate Optimization",
      "Sales Funnel Optimization",
    ],
    benefits: [
      "Qualified Lead Pipeline",
      "Reduced Customer Acquisition Cost",
      "Higher Conversion Rates",
      "Revenue Growth",
    ],
  },
] as const;

export const STATS = [
  { label: "Years of Experience", value: 15, suffix: "+" },
  { label: "Satisfied Clients", value: 500, suffix: "+" },
  { label: "Projects Completed", value: 1200, suffix: "+" },
  { label: "Countries Served", value: 12, suffix: "+" },
] as const;

export const TESTIMONIALS = [
  {
    id: "1",
    name: "Rajesh Kumar",
    designation: "Procurement Head",
    company: "BHEL Hyderabad",
    content: "Sree Manikanta Cables has been our trusted partner for over 8 years. Their consistent quality, on-time delivery, and technical support make them our preferred vendor for all cable requirements.",
    image: "/images/testimonials/rajesh.jpg",
    rating: 5,
  },
  {
    id: "2",
    name: "Priya Sharma",
    designation: "Electrical Engineering Lead",
    company: "L&T Construction",
    content: "The technical expertise and product range of Sree Manikanta Cables is impressive. Their team helped us select the right cables for our metro project, ensuring compliance with all specifications.",
    image: "/images/testimonials/priya.jpg",
    rating: 5,
  },
  {
    id: "3",
    name: "Amit Patel",
    designation: "Plant Manager",
    company: "Tata Power Solar",
    content: "We've been using their solar cables for multiple installations. The UV resistance and durability in harsh environments have exceeded our expectations. Highly recommended for renewable energy projects.",
    image: "/images/testimonials/amit.jpg",
    rating: 5,
  },
  {
    id: "4",
    name: "Sunita Reddy",
    designation: "Senior Purchase Manager",
    company: "NTPC Limited",
    content: "Professional approach, competitive pricing, and adherence to delivery schedules. Their ISO certifications and quality testing facilities give us confidence in every order we place.",
    image: "/images/testimonials/sunita.jpg",
    rating: 5,
  },
] as const;

export const FOOTER_SECTIONS = [
  {
    title: "Company",
    links: [
      { label: "About Us", href: "/about" },
      { label: "Manufacturing", href: "/manufacturing" },
      { label: "Quality", href: "/quality" },
      { label: "Careers", href: "/careers" },
      { label: "CSR", href: "/csr" },
    ],
  },
  {
    title: "Products",
    links: [
      { label: "Industrial Cables", href: "/products/industrial-cables" },
      { label: "Control Cables", href: "/products/control-cables" },
      { label: "LT Power Cables", href: "/products/lt-power-cables" },
      { label: "Instrumentation Cables", href: "/products/instrumentation-cables" },
      { label: "All Products", href: "/products" },
    ],
  },
  {
    title: "Support",
    links: [
      { label: "Technical Support", href: "/support" },
      { label: "Product Catalog", href: "/catalog" },
      { label: "Certifications", href: "/quality" },
      { label: "FAQs", href: "/faq" },
      { label: "Contact Us", href: "/contact" },
    ],
  },
  {
    title: "Resources",
    links: [
      { label: "Blog & News", href: "/blog" },
      { label: "Case Studies", href: "/case-studies" },
      { label: "White Papers", href: "/white-papers" },
      { label: "Standards & Codes", href: "/standards" },
      { label: "Digital Presence", href: "/digital" },
    ],
  },
] as const;

export const SOCIAL_LINKS = [
  { name: "LinkedIn", href: "https://linkedin.com/company/sreemanikantacables", icon: "linkedin" },
  { name: "Twitter", href: "https://twitter.com/sreemanikanta", icon: "twitter" },
  { name: "Facebook", href: "https://facebook.com/sreemanikantacables", icon: "facebook" },
  { name: "YouTube", href: "https://youtube.com/@sreemanikantacables", icon: "youtube" },
  { name: "Instagram", href: "https://instagram.com/sreemanikantacables", icon: "instagram" },
] as const;

export const WORKING_HOURS = [
  { day: "Monday - Friday", hours: "9:00 AM - 6:00 PM" },
  { day: "Saturday", hours: "9:00 AM - 2:00 PM" },
  { day: "Sunday", hours: "Closed" },
] as const;